// Code generated by "stringer -type Flag"; DO NOT EDIT

package cmd

import "fmt"

const _Flag_name = "MustPanicMustExitWarnNoAnnotateStdErrInResultPassThroughPassThroughStdOutPassThroughStdErrPassThroughStdInTrimSpaceFirstLineStrictVerbose"

var _Flag_index = [...]uint8{0, 9, 17, 21, 31, 45, 56, 73, 90, 106, 115, 124, 130, 137}

func (i Flag) String() string {
	i -= 1
	if i >= Flag(len(_Flag_index)-1) {
		return fmt.Sprintf("Flag(%d)", i+1)
	}
	return _Flag_name[_Flag_index[i]:_Flag_index[i+1]]
}
